/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  
  // 1. The DM Master Sidebar (Only visible when you are in the dm-master folder)
  dmSidebar: [
    {
      type: 'autogenerated',
      dirName: 'dm-master', // Generates sidebar from the dm-master folder
    },
  ],

  // 2. Campaign 1 Sidebar (Public Legacy)
  legacySidebar: [
    {
      type: 'autogenerated',
      dirName: 'legacy-shattered-balance', 
    },
  ],

  // 3. Campaign 2 Sidebar (Wagonwood Players Only)
  wagonwoodSidebar: [
    {
      type: 'autogenerated',
      dirName: 'stained-guard-xj7k9p', 
    },
  ],

  // 4. Campaign 3 Sidebar (Black Orchid Players Only)
  tormalonSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tormalon-pain-v4m2zq', 
    },
  ],
};

export default sidebars;